server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_sync
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.xdchen.order.model

taobao:
  refreshTokenUrl: 'http://container.open.taobao.com/container/refresh'
  tbPostSessionUrl: ''
  topBoxApiUrl: ''
  topSecurityUrl: ''
  topBoxAutUrl: ''
  topBoxAppKey: ''
  topBoxAppSecret: ''
  redirectUri: ''
  topBoxAppKeyForBuyer: ''
  topBoxAppSecretForBuyer: ''
  topToken: ''

jingdong: